export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGUP_FAIL = 'SIGUP_FAIL'

export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS'
export const ACTIVATION_FAILED = 'ACTIVATION_FAILED'
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';